on:
  push:
jobs:
  deploy:
    name: Deploy to OVH
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build assets
        run: npm run build
      - name: Deploy to OVH
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          dry-run: 'true'
          server: ftp.cluster031.hosting.ovh.net
          username: jfcpcey
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./src
          server-dir: prod/wp-content/themes/weinrich
